# Generated by Django 5.1.6 on 2025-03-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_category_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(default='G Cash', max_length=100),
            preserve_default=False,
        ),
    ]
