# Generated by Django 5.1.6 on 2025-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
