# Generated by Django 5.1.6 on 2025-03-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
