# Generated by Django 5.1.6 on 2025-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile_payment_method_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_method',
        ),
       
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        
    ]
